[log]
level = "debug"
count = 8
size = 8  # mb


# [[targets]]
# path = "./share/电影/纪录片/国家地理.伟大工程巡礼系列National.Geographic.Megastructures.720p.HDTV"
# type = "smb"  # smb,local
# suffixes = ["mp4", "mkv", "avi", "wmv"]
# search_recursive = true
# # if smb:
# smb_user = ""
# smb_password = ""

[[targets]]
path = "F:\\FC2PPV-2711719"
type = "smb"  # smb,local
suffixes = ["mp4", "mkv", "avi", "wmv"]
# if smb:
smb_user = ""
smb_password = ""
search_recursive = true

[ffmpeg]
binary_path = "./ffmpeg/ffmpeg.exe"            # full path
tmp_path = "./tmp/"

[whisper]
# for more detail, please read github.com/openai/whisper/__init__.py,transcribe.py
model_path = "models"  # where to find the models, where to place the models when download
model_name = "large-v2"  # tiny[.en], small[.en], medium[.en], large_v2  for detail, please read README.md
model_device = "cuda"  # cuda,cpu,""  use "" to let whisper auto choose cuda or cpu


[translate]
enable = true  # true,false
target_language = "zh-CN"
api = ["google", "bing", "Sogou", "Iflytek"]  # https://github.com/UlionTse/translators
fail_hint = "translation failed"  # "","translation failed"

[srt]
overwrite = true  # true,false overwrite the existence srt
bilingual = true  # true,false translated words in first line, while the origin lying on second line
