[[targets]]
path = ""
type = "smb"  # smb,local
suffixes = ["mp4", "mkv", "avi", "wmv"]
# if smb:
smb_user = ""
smb_password = ""

[ffmpeg]
binary = ""            # full path
audio_tmp = ""

[whisper]
# for more detail, please read github.com/openai/whisper/__init__.py,transcribe.py
model_path = "E:\wisper\models"  # where to find the models, where to place the models when download
model_name = "medium"  # tiny[.en], small[.en], medium[.en], large_v2  for detail, please read README.md
model_device = ""  # cuda,cpu,""  use "" to let whisper auto choose cuda or cpu


[translate]
enable = true  # true,false
target_language = "zh"
api = ["google", "bing", "Sogou", "Baidu", "Iflytek"]  # https://github.com/UlionTse/translators
fail_action = ""  # "","translation failed"

[srt]
overwrite = true  # true,false overwrite the existence srt
bilingual = true  # true,false translated words in first line, while the origin lying on second line